version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: pz
      POSTGRES_USER: pz
      POSTGRES_PASSWORD: pz
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local